---
- name: Include variable overrides
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
        - "vars/{{ ansible_distribution }}.yaml"
        - "vars/{{ ansible_os_family }}.yaml"
        - "vars/main.yaml"
  tags: nfssetup

- name: Import nfs server depend tasks
  ansible.builtin.include_tasks: nfs-server.yaml
  when: kind == "server"
  tags: nfssetup

- name: Import Manage firewall tasks - allow nfs ports
  ansible.builtin.include_tasks: firewall.yaml
  when: 
    - kind == "server"
    - nfs_manage_firewall | bool == true
  tags: nfssetup

- name: Override sid on hana setup
  ansible.builtin.set_fact:
    sid: "{{ hana_sid }}"
  when: hana_sid is defined

- name: Override sid on s4 setup
  ansible.builtin.set_fact:
    sid: "{{ x4_sid }}"
  when: x4_sid is defined

- name: Import nfs client depend tasks
  ansible.builtin.include_tasks: nfs-client.yaml
  when: kind == "client"

